### ISSUE TITLE
How to use menus in Symfony 4

### ISSUE THREAD

**Issue by Aerendir** [KnpLabs/KnpMenu#283]
Before the bundlle system deprecation, I used to do this:

    {{ knp_menu_render('AppBundle:Builder:mainMenu') }}

But now that `AppBundle` doesn't exist anymore, how can I render the menu?

Obviously this syntax doesn't work...

**Comment by stof** [comment]
I recommend registering menu builders as services

**Comment by Aerendir** [comment]
Yes, I'm reading just this part of the documentation and it seems to be the only way I have to make it work in Symfony 4...

So you confirm me this is the right path to follow?

**Comment by Aerendir** [comment]
This is the error that currently I'm getting:

`Unable to find template "knp_menu.html.twig" (looked into: /Users/Aerendir/Documents/JooServer/_Projects/MyApp/templates, /Users/Aerendir/Documents/JooServer/_Projects/MyApp/templates, /Users/Aerendir/Documents/JooServer/_Projects/MyApp/vendor/symfony/twig-bridge/Resources/views/Form) in @KnpMenu/menu.html.twig at line 1.`

Now, the missed template exists in the package `knp-menu`, but not in the package `knp_menu_bundle`.

It seems that `knp-menu` isn't registered as a bundle and so the that base template cannot be found...

Any ideas?

**Comment by sess16** [comment]
Is it works @Aerendir ?

**Comment by Aerendir** [comment]
@sess16 , currently I stopped the use of SF4 as of this problem: I didn't fixed it nor found a way to make it work. But I run out of time to dedicate to this...

**Comment by iflorespaz** [comment]
Hello,

when KnpMenu will be available to use with SF4?
I check every day for an update but nothing is done :(

Do you have a roadmap for this bundle?

Best regards,
Isaac

**Comment by BoShurik** [comment]
twig.yaml
```
twig:
    paths:
        - '%kernel.project_dir%/templates'
        - '%kernel.project_dir%/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views'

    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
```

**Comment by Aerendir** [comment]
@BoShurik , really good! As told, I'm not working on the migration now, but I will try this solution ASAP. Anyway this works for sure as it hard fixes the problem of the missed template.

But the real question remains: why is this template missed?

**Comment by Aerendir** [comment]
@iflorespaz , it works with SF4, but some workarounds as the one suggested by @BoShurik is required.

The best thing you can do, is try to use the bundle with SF4 and see where you stop, then ask here for a solution: this will help all of us to make the bundle fully work in SF4.

**Comment by BoShurik** [comment]
> But the real question remains: why is this template missed?

Because it is in `knp-menu` not in `knp-menu-bundle` I think

**Comment by Aerendir** [comment]
Yes, but in SF3 it works... so the question is relevant to update the bundle and make it load he template also in SF4.

**Comment by nickicool** [comment]
@BoShurik, thank you for this simple and usefull solution!

**Comment by codedmonkey** [comment]
I did some more digging. The problem is that feature relies on a `symfony/templating` dependency.

    composer require symfony/templating

and it needs to be configured in `config/packages/framework.yaml`:

    framework:
        # ....
        templating:
            engines:
              - 'twig'

**Comment by Aerendir** [comment]
@codedmonkey many many thank you! I think that discover this problem was really a pain and so I can only thell you: "Thankyou"!

**Comment by stof** [comment]
https://github.com/KnpLabs/KnpMenuBundle/issues/374 is tracking this in the bundle.

**Comment by codedmonkey** [comment]
Now that problem is fixed, this can either be closed or is it worth discussing having autowired builders incorporated in the bundle?

**Comment by Aerendir** [comment]
I think this can be closed as it is already tracked in KnpLabs/KnpMenuBundle#374.

**Comment by GermerCarsten** [comment]
I just came across this problem and this isn't resolved, yet, right? The documentation at https://symfony.com/doc/current/bundles/KnpMenuBundle/index.html doesn't work.
This ist still a problem if one stumbles over that - change the documentation or fox the software?

**Comment by danyal14** [comment]
Hi Guys,

Any one, any luck?
I moved my Menu folder under src and still gets this error.
{{ knp_menu_render('Menu/MenuBuilder:mainMenu') }}
An exception has been thrown during the rendering of a template ("The menu "Menu/MenuBuilder:mainMenu" is not defined.").

**Comment by Gounlaf** [comment]
@danyal14 

1. Register your menu as a service
2. Inject your menu in your template (if you need it in your layout, the only way I found is too declare a global twig variable)
3. `{{ knp_menu_render(your_menu) }}`; where `your_menu` is already an instance of `Knp\Menu\ItemInterface`; it avoid `Knp\Menu\Twig\Helper` (the one called by `knp_menu_render`) to search for a bundle

If then you got the error
> Unable to find template "KnpMenuBundle::menu.html.twig"
do like @codedmonkey said above:

`composer require symfony/templating`

config/packages/framework.yaml:

```
framework:
    # ....
    templating:
        engines:
          - 'twig'
```

**Comment by Kronhyx** [comment]
@Aerendir you can use this provider https://github.com/Kronhyx/KnpMenuBundle/blob/master/Provider/BuilderAliasProvider.php
instead call **knp_menu_get('AppBundle:HeaderMenu:Search')** use **knp_menu_get('App:HeaderMenu:Search')**

**Comment by Aerendir** [comment]
@Kronhyx , thank you for the suggestion... I've solved using menus as services and it works very well...

**Comment by cre8izm** [comment]
@Aerendir does it recognise the current link? Using menu as service with SF4 made it work but it doesn't recognise the current link.

**Comment by cre8izm** [comment]
@Aerendir, Thanks.

Anyone else experiencing the issue of current link not being recognised?

**Comment by flopp26** [comment]
@cre8izm , I have same trouble, all my link has class "current"

**Comment by goulashsoup** [comment]
I just build a custom Menu extension to replace `knp_menu_get`:

    <?php

    declare(strict_types=1);

    namespace App\Twig\KnpMenu;

    use Knp\Menu\ItemInterface;
    use Symfony\Component\DependencyInjection\ContainerInterface;
    use Twig\TwigFunction;
    use Twig\Extension\AbstractExtension;

    class AppMenuExtension extends AbstractExtension
    {
        /**
        * @var ContainerInterface
        */
        private $container;

        public function __construct(ContainerInterface $container)
        {

            $this->container = $container;
        }

        public function getFunctions()
        {
            return [
                new TwigFunction('app_knp_menu_get', [$this, 'getMenu']),
            ];
        }

        public function getMenu(string $menu, array $path = [], array $options = []): ItemInterface
        {
            $menuBuilderName = substr($menu, 0, strrpos($menu, '::'));
            $actionName = substr($menu, strrpos($menu, '::')+2);

            $menuBuilder = $this->container->get($menuBuilderName);
            $menuBuilder->setContainer($this->container); // Inject container with ContainerAwareTrait
            $knpMenuFactory = $this->container->get('knp_menu.factory');

            return $menuBuilder->{$actionName}($knpMenuFactory, $options);
        }
    }

Usage:

    {% set menuItem = app_knp_menu_get('App\\Menu\\EnumeratedContactMenuBuilder::createListTools', [], { 'routePrefix': routePrefix, 'type': type }) %}
    {{ knp_menu_render(menuItem) }}

The `MenuBuilder` has to be registered as a service via Symfony autoconfigure.

**Comment by tchafack** [comment]
> As a workaround
> 
> twig.yaml
> 
> ```
> twig:
>     paths:
>         - '%kernel.project_dir%/templates'
>         - '%kernel.project_dir%/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views'
> 
>     debug: '%kernel.debug%'
>     strict_variables: '%kernel.debug%'
> ```

This is it ! Thanks @BoShurik 

Update in 2025 

**Twig conf :**

```
twig:
...
    paths:
        'vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views': 'knp'
 ...
 ```

**In template :** 

```
{% extends '@knp/knp_menu.html.twig' %}
 ```
